:wrench: Remove "type": "module" from package.json in oder to use cjs by default
See https://ja.vitejs.dev/guide/troubleshooting.html

Result:

$ npx vite build
✘ [ERROR] Failed to resolve "@sveltejs/kit/vite". This package is ESM only but it was tried to load by `require`. See http://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details. [plugin externalize-deps]

    node_modules/esbuild/lib/main.js:1373:27:
      1373 │         let result = await callback({
           ╵                            ^

    at file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:66268:43
    at requestCallbacks.on-resolve ($HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:1373:28)
    at handleRequest ($HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:729:19)
    at handleIncomingPacket ($HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:755:7)
    at Socket.readFromStdout ($HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Readable.push (node:internal/streams/readable:253:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:66243:27)
    at handlePlugins ($HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:1292:21)
    at buildOrContextImpl ($HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:978:5)
    at Object.buildOrContext ($HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:786:5)
    at $HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:2177:15
    at new Promise (<anonymous>)
    at Object.build ($HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:2176:25)
    at build ($HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:2025:51)
    at bundleConfigFile (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:66194:26)

  The plugin "externalize-deps" was triggered by this import

    vite.config.ts:1:354:
      1 │ ...dbox/todo_with_sveltekit_and_goa/vite.config.ts";import { sveltekit } from '@sveltejs/kit/vite';
        ╵                                                                               ~~~~~~~~~~~~~~~~~~~~

failed to load config from $HOME/sandbox/todo_with_sveltekit_and_goa/vite.config.ts
error during build:
Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:1373:27: ERROR: [plugin: externalize-deps] Failed to resolve "@sveltejs/kit/vite". This package is ESM only but it was tried to load by `require`. See http://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details.
    at failureErrorWithLog ($HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:1649:15)
    at $HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks ($HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:1484:45)
    at buildResponseToResult ($HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:1056:7)
    at $HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:1085:16
    at responseCallbacks.<computed> ($HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket ($HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout ($HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:343:12)