:wrench: Use vitePluginRequire in vite.config.ts
$ npx vite build

vite v4.5.0 building SSR bundle for production...
✓ 80 modules transformed.
✓ built in 372ms
"default" is not exported by "src/lib/server/goagen_goa_todo_example_todos_pb.cjs", imported by "src/lib/server/goagen_goa_todo_example_todos_grpc_pb.cjs".
file: $HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/server/goagen_goa_todo_example_todos_grpc_pb.cjs:13:7
11: 'use strict';
12: var grpc = require('@grpc/grpc-js');
13: var goagen_goa_todo_example_todos_pb = require('./goagen_goa_todo_example_todos_pb');
           ^
14:
15: function serialize_todos_CreateRequest(arg) {
error during build:
RollupError: "default" is not exported by "src/lib/server/goagen_goa_todo_example_todos_pb.cjs", imported by "src/lib/server/goagen_goa_todo_example_todos_grpc_pb.cjs".
    at error (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
    at Module.traceVariable (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
    at ModuleScope.findVariable (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
    at Identifier.bind (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:8319:40)
    at VariableDeclarator.bind (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at VariableDeclaration.bind (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
    at Program.bind (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
    at Module.bindReferences (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:13741:18)
    at Graph.sortModules (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:25853:20)