:package: $ npm i google-protobuf
Result:

$ npx vite build

vite v4.5.0 building SSR bundle for production...
✓ 86 modules transformed.

vite v4.5.0 building for production...
[plugin:vite:resolve] Module "util" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/apisvr/client.ts". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "tls" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/channel-credentials.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "process" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/logging.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "http2" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/server.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "dns" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/resolver-dns.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "util" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/resolver-dns.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "net" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/resolver-dns.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "net" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/channelz.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "net" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/resolver-ip.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "events" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/call.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "stream" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/call.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "fs" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/tls-helpers.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "events" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/server-call.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "http2" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/server-call.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "stream" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/server-call.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "zlib" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/server-call.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "util" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/server-call.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "net" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/subchannel-address.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "os" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/service-config.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "zlib" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/compression-filter.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "http" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/http_proxy.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "tls" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/http_proxy.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "url" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/http_proxy.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "http2" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/load-balancing-call.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "http2" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/transport.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "tls" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/transport.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "net" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/transport.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "http2" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/subchannel-call.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "os" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/grpc-js/build/src/subchannel-call.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "fs" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/proto-loader/build/src/util.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "path" has been externalized for browser compatibility, imported by "$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/@grpc/proto-loader/build/src/util.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
node_modules/@protobufjs/inquire/index.js (12:18) Use of eval in "node_modules/@protobufjs/inquire/index.js" is strongly discouraged as it poses security risks and may cause issues with minification.
node_modules/google-protobuf/google-protobuf.js (27:206) Use of eval in "node_modules/google-protobuf/google-protobuf.js" is strongly discouraged as it poses security risks and may cause issues with minification.
node_modules/google-protobuf/google-protobuf.js (29:315) Use of eval in "node_modules/google-protobuf/google-protobuf.js" is strongly discouraged as it poses security risks and may cause issues with minification.
node_modules/google-protobuf/google-protobuf.js (48:475) Use of eval in "node_modules/google-protobuf/google-protobuf.js" is strongly discouraged as it poses security risks and may cause issues with minification.
✓ 302 modules transformed.
✓ built in 812ms
"promisify" is not exported by "__vite-browser-external", imported by "src/lib/apisvr/client.ts".
file: $HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/apisvr/client.ts:1:9
1: import { promisify } from 'util';
            ^
2: import { credentials } from '@grpc/grpc-js';
[vite-plugin-sveltekit-compile] "promisify" is not exported by "__vite-browser-external", imported by "src/lib/apisvr/client.ts".
file: $HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/apisvr/client.ts:1:9
1: import { promisify } from 'util';
            ^
2: import { credentials } from '@grpc/grpc-js';
✓ built in 1.72s
error during build:
RollupError: "promisify" is not exported by "__vite-browser-external", imported by "src/lib/apisvr/client.ts".
    at error (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
    at Module.traceVariable (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
    at ModuleScope.findVariable (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
    at ReturnValueScope.findVariable (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at ChildScope.findVariable (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at Identifier.bind (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:8319:40)
    at CallExpression.bind (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at CallExpression.bind (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:9890:15)
    at MemberExpression.bind (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)