:package: $ npm i google-protobuf
$ npx vite build

vite v4.5.0 building SSR bundle for production...
✓ 104 modules transformed.

vite v4.5.0 building for production...
node_modules/@protobufjs/inquire/index.js (12:18) Use of eval in "node_modules/@protobufjs/inquire/index.js" is strongly discouraged as it poses security risks and may cause issues with minification.
node_modules/google-protobuf/google-protobuf.js (27:206) Use of eval in "node_modules/google-protobuf/google-protobuf.js" is strongly discouraged as it poses security risks and may cause issues with minification.
node_modules/google-protobuf/google-protobuf.js (29:315) Use of eval in "node_modules/google-protobuf/google-protobuf.js" is strongly discouraged as it poses security risks and may cause issues with minification.
node_modules/google-protobuf/google-protobuf.js (48:475) Use of eval in "node_modules/google-protobuf/google-protobuf.js" is strongly discouraged as it poses security risks and may cause issues with minification.
✓ 486 modules transformed.
.svelte-kit/output/client/_app/version.json                               0.03 kB │ gzip:   0.05 kB
.svelte-kit/output/client/_app/immutable/assets/remove.74788b08.svg       0.42 kB │ gzip:   0.25 kB
.svelte-kit/output/client/.vite/manifest.json                             2.56 kB │ gzip:   0.47 kB
.svelte-kit/output/client/_app/immutable/assets/2.d95034d9.css            0.41 kB │ gzip:   0.26 kB
.svelte-kit/output/client/_app/immutable/nodes/0.be039bf9.js              0.60 kB │ gzip:   0.38 kB
.svelte-kit/output/client/_app/immutable/nodes/1.b080d3f0.js              1.03 kB │ gzip:   0.59 kB
.svelte-kit/output/client/_app/immutable/chunks/singletons.04088ea4.js    2.86 kB │ gzip:   1.46 kB
.svelte-kit/output/client/_app/immutable/chunks/index.ddd021ae.js         5.54 kB │ gzip:   2.35 kB
.svelte-kit/output/client/_app/immutable/entry/app.2df793c2.js            5.85 kB │ gzip:   2.32 kB
.svelte-kit/output/client/_app/immutable/entry/start.00c7e29e.js         24.89 kB │ gzip:   9.80 kB
.svelte-kit/output/client/_app/immutable/chunks/scheduler.b4357ffa.js    32.07 kB │ gzip:  10.12 kB
.svelte-kit/output/client/_app/immutable/nodes/2.72ebb289.js            834.35 kB │ gzip: 205.33 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 2.09s
.svelte-kit/output/server/_app/immutable/assets/remove.74788b08.svg   0.42 kB
.svelte-kit/output/server/.vite/manifest.json                         2.75 kB
.svelte-kit/output/server/_app/immutable/assets/_page.a9cb30b2.css    0.43 kB
.svelte-kit/output/server/internal.js                                 0.19 kB
.svelte-kit/output/server/entries/fallbacks/layout.svelte.js          0.27 kB
.svelte-kit/output/server/entries/pages/_page.server.ts.js            0.33 kB
.svelte-kit/output/server/entries/endpoints/todo/_server.ts.js        0.54 kB
.svelte-kit/output/server/entries/endpoints/todo/_id_/_server.ts.js   0.68 kB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js           0.92 kB
.svelte-kit/output/server/chunks/database.js                          1.01 kB
.svelte-kit/output/server/entries/pages/_page.svelte.js               1.43 kB
.svelte-kit/output/server/chunks/index.js                             1.99 kB
.svelte-kit/output/server/chunks/ssr.js                               3.72 kB
.svelte-kit/output/server/chunks/index2.js                            4.21 kB
.svelte-kit/output/server/chunks/internal.js                         10.18 kB
.svelte-kit/output/server/chunks/client.js                           77.57 kB
.svelte-kit/output/server/index.js                                   88.33 kB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-auto
  Could not detect a supported production environment. See https://kit.svelte.dev/docs/adapters to learn how to configure your app to run on the platform of your choosing
  ✔ done
✓ built in 3.59s

DEV SERVER

$ npm run dev

> todo-with-sveltekit-and-goa@0.0.1 dev
> vite dev

  VITE v4.5.0  ready in 467 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Failed to load url ../protos/goagen_goa_todo_example_todos_grpc_pb (resolved id: ../protos/goagen_goa_todo_example_todos_grpc_pb) in $HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/apisvr/client.ts. Does the file exist?
18:03:37 [vite] Error when evaluating SSR module /src/lib/apisvr/client.ts: failed to import "../protos/goagen_goa_todo_example_todos_grpc_pb"
|- Error: Failed to load url ../protos/goagen_goa_todo_example_todos_grpc_pb (resolved id: ../protos/goagen_goa_todo_example_todos_grpc_pb) in $HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/apisvr/client.ts. Does the file exist?
    at loadAndTransform (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55015:21)

18:03:37 [vite] Error when evaluating SSR module /src/routes/+page.server.ts: failed to import "/src/lib/apisvr/client.ts"
|- Error: Failed to load url ../protos/goagen_goa_todo_example_todos_grpc_pb (resolved id: ../protos/goagen_goa_todo_example_todos_grpc_pb) in $HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/apisvr/client.ts. Does the file exist?
    at loadAndTransform (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55015:21)

Error: Failed to load url ../protos/goagen_goa_todo_example_todos_grpc_pb (resolved id: ../protos/goagen_goa_todo_example_todos_grpc_pb) in $HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/apisvr/client.ts. Does the file exist?
    at loadAndTransform (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55015:21) {
  code: 'ERR_LOAD_URL'
}
Failed to load url ../protos/goagen_goa_todo_example_todos_pb (resolved id: ../protos/goagen_goa_todo_example_todos_pb) in $HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/apisvr/client.ts. Does the file exist?