:package: $ npm i google-protobuf
$ npx vite build

vite v4.5.0 building SSR bundle for production...
✓ 86 modules transformed.

vite v4.5.0 building for production...
✓ 62 modules transformed.
.svelte-kit/output/client/_app/version.json                              0.03 kB │ gzip: 0.05 kB
.svelte-kit/output/client/_app/immutable/assets/remove.74788b08.svg      0.42 kB │ gzip: 0.25 kB
.svelte-kit/output/client/.vite/manifest.json                            2.56 kB │ gzip: 0.48 kB
.svelte-kit/output/client/_app/immutable/assets/2.d95034d9.css           0.41 kB │ gzip: 0.26 kB
.svelte-kit/output/client/_app/immutable/nodes/0.8138219e.js             0.60 kB │ gzip: 0.38 kB
.svelte-kit/output/client/_app/immutable/nodes/1.6734fc87.js             1.03 kB │ gzip: 0.59 kB
.svelte-kit/output/client/_app/immutable/chunks/scheduler.e108d1fd.js    2.16 kB │ gzip: 1.02 kB
.svelte-kit/output/client/_app/immutable/chunks/singletons.35542b13.js   2.86 kB │ gzip: 1.46 kB
.svelte-kit/output/client/_app/immutable/nodes/2.7e203668.js             3.87 kB │ gzip: 1.90 kB
.svelte-kit/output/client/_app/immutable/chunks/index.c1d64499.js        5.54 kB │ gzip: 2.34 kB
.svelte-kit/output/client/_app/immutable/entry/app.ed077dc0.js           5.85 kB │ gzip: 2.32 kB
.svelte-kit/output/client/_app/immutable/entry/start.3d4c556c.js        24.89 kB │ gzip: 9.80 kB
✓ built in 257ms
.svelte-kit/output/server/_app/immutable/assets/remove.74788b08.svg   0.42 kB
.svelte-kit/output/server/.vite/manifest.json                         2.40 kB
.svelte-kit/output/server/_app/immutable/assets/_page.a9cb30b2.css    0.43 kB
.svelte-kit/output/server/internal.js                                 0.19 kB
.svelte-kit/output/server/entries/fallbacks/layout.svelte.js          0.24 kB
.svelte-kit/output/server/entries/endpoints/todo/_server.ts.js        0.53 kB
.svelte-kit/output/server/entries/endpoints/todo/_id_/_server.ts.js   0.67 kB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js           0.89 kB
.svelte-kit/output/server/entries/pages/_page.server.ts.js            0.99 kB
.svelte-kit/output/server/entries/pages/_page.svelte.js               1.37 kB
.svelte-kit/output/server/chunks/index.js                             1.99 kB
.svelte-kit/output/server/chunks/ssr.js                               3.70 kB
.svelte-kit/output/server/chunks/internal.js                         10.16 kB
.svelte-kit/output/server/chunks/grpc_client.js                      52.64 kB
.svelte-kit/output/server/index.js                                   88.30 kB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-auto
  Could not detect a supported production environment. See https://kit.svelte.dev/docs/adapters to learn how to configure your app to run on the platform of your choosing
  ✔ done
✓ built in 1.53s

DEV SERVER

$ npm run dev

> todo-with-sveltekit-and-goa@0.0.1 dev
> vite dev

  VITE v4.5.0  ready in 450 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Failed to load url ./goagen_goa_todo_example_todos_pb (resolved id: ./goagen_goa_todo_example_todos_pb) in $HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/server/grpc_client.ts. Does the file exist?
20:09:05 [vite] Error when evaluating SSR module /src/lib/server/goagen_goa_todo_example_todos_grpc_pb.cjs:
|- ReferenceError: require is not defined
    at $HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/server/goagen_goa_todo_example_todos_grpc_pb.cjs:12:12
    at instantiateModule (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:15)

20:09:05 [vite] Error when evaluating SSR module /src/lib/server/grpc_client.ts: failed to import "/src/lib/server/goagen_goa_todo_example_todos_grpc_pb.cjs"
|- ReferenceError: require is not defined
    at $HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/server/goagen_goa_todo_example_todos_grpc_pb.cjs:12:12
    at instantiateModule (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:15)

20:09:05 [vite] Error when evaluating SSR module $HOME/sandbox/todo_with_sveltekit_and_goa/src/routes/todo/+server.ts: failed to import "/src/lib/server/grpc_client.ts"
|- ReferenceError: require is not defined
    at $HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/server/goagen_goa_todo_example_todos_grpc_pb.cjs:12:12
    at instantiateModule (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:15)

ReferenceError: require is not defined
    at $HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/server/goagen_goa_todo_example_todos_grpc_pb.cjs:12:12
    at instantiateModule (file://$HOME/sandbox/todo_with_sveltekit_and_goa/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:15)