:sparkles: Remove extension of required filename
$ npx vite build

vite v4.5.0 building SSR bundle for production...
✓ 77 modules transformed.
✓ built in 246ms
[vite:load-fallback] Could not load $HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/protos/goagen_goa_todo_example_todos_grpc_pb (imported by src/lib/apisvr/client.ts): ENOENT: no such file or directory, open '$HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/protos/goagen_goa_todo_example_todos_grpc_pb'
error during build:
Error: Could not load $HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/protos/goagen_goa_todo_example_todos_grpc_pb (imported by src/lib/apisvr/client.ts): ENOENT: no such file or directory, open '$HOME/sandbox/todo_with_sveltekit_and_goa/src/lib/protos/goagen_goa_todo_example_todos_grpc_pb'